### ISSUE TITLE
Bug with off screen click release

### ISSUE THREAD

**Issue by ShashankVenkatramani** [cse110-sp23-group16/cse110-sp23-group16#109] opened 2023-06-07 05:45 UTC
**Describe the bug**
On the skymap page, if you click down while on the skymap, drag, and release when the mouse is off of the browser, returning the cursor back to the screen causes it to continue to drag.

**To Reproduce**

1. Go to [skymap page](https://cse110-sp23-group16.github.io/cse110-sp23-group16/source/pages/skymap_page/skymap.html)
2. Click and hold on skymap to begin drag
3. Start dragging until off of canvas window
4. Release
5. Move it back to canvas window and drag is continued

**Expected behavior**
The drag should end on a click release

**Comment by khushijpatel** [comment] 2023-06-09 23:29
Issue has been fixed with work on another issue, I am unable to reproduce the bug.

**Closed as completed by khushijpatel** 2023-06-09 23:29 UTC
Labels: bug, UI
